/* Generated from source/security-mode.json. Do not edit this file directly. */
(function(root){'use strict';const mode=Object.freeze({pinRequired:false});if(typeof module==='object'&&module.exports)module.exports=mode;else Object.defineProperty(root,'AluvisionSecurityMode',{value:mode,writable:false});})(typeof globalThis!=='undefined'?globalThis:this);
